################################################################################
# File version information:
# $Id$
# $Revision$
# $HeadURL$
# $Date$
################################################################################

=pod

=head1 NAME

C<check_updates> - a Nagios plugin to check if Red Hat or Fedora system
is up-to-date

=head1 DESCRIPTION

check_updates is a Nagios plugin to check if Red Hat or Fedora system
is up-to-date

=head1 VERSION

Version 1.4.13

=head1 SYNOPSIS

  check_updates [OPTIONS]

  -?, --usage
    Print usage information
  -h, --help
    Print detailed help screen
  -V, --version
    Print version information
  --extra-opts=[<section>[@<config_file>]]
    Section and/or config_file from which to load extra options (may repeat)
  --boot-check
    Check if the machine was booted with the newest kernel (default)
  --no-boot-check
    do not complain if the machine was booted with an old kernel
  -w, --warning=INTEGER
    Exit with WARNING status if more than INTEGER updates are available
  -c, --critical=INTEGER
    Exit with CRITICAL status if more than INTEGER updates are available
  -t, --timeout=INTEGER
    Seconds before plugin times out (default: 15)
  -v, --verbose
    Show details for command-line debugging (can repeat up to 3 times)

=head1 OPTIONS

  -?, --usage                              Print usage information

  -h, --help                               Print detailed help screen

  -V, --version                            Print version information

  --extra-opts=[<section>[@<config_file>]] Section and/or config_file from which to load extra options (may repeat)

  --boot-check                             Check if the machine was booted with the newest kernel (default)

  --no-boot-check                          do not complain if the machine was booted with an old kernel

  -w, --warning=INTEGER                    Exit with WARNING status if more than INTEGER updates are available

  -c, --critical=INTEGER                   Exit with CRITICAL status if more than INTEGER updates are available

  -t, --timeout=INTEGER                    Seconds before plugin times out (default: 15)

  -v, --verbose                            Show details for command-line debugging (can repeat up to 3 times)

=head1 EXAMPLE

 check_updates

check_updates checks if the system is up-to-date

=head1 DIAGNOSTICS

You can specify multiple --verbose options to increase the program
verbosity.

=head1 EXIT STATUS

0 if OK, 1 in case of a warning, 2 in case of a critical status and 3
in case of an unkown problem

=head1 DEPENDENCIES

check_updates depends on

=over 4

=item * Carp

=item * English

=item * Getopt::Long

=item * Nagios::Plugin

=item * Nagios::Plugin::Getopt

=item * Nagios::Plugin::Threshold

=item * POSIX

=item * Readonly

=item * Sort::Versions

=back

=head1 INCOMPATIBILITIES

None reported.

=head1 SEE ALSO

Nagios documentation

=head1 BUGS AND LIMITATIONS

No bugs have been reported.

Please report any bugs or feature requests to matteo.corti@id.ethz.ch,
or through the web interface at
http://trac.id.ethz.ch/projects/nagios_plugins/newticket?component=check_updates

=head1 AUTHOR

Matteo Corti <matteo.corti@id.ethz.ch>

=head1 LICENSE AND COPYRIGHT

Copyright (c) 2007-2010, Matteo Corti

This module is free software; you can redistribute it and/or modify it
under the terms of GNU general public license (gpl) version 3 or (at
your option) any later version.
See the LICENSE file for details.

=head1 DISCLAIMER OF WARRANTY

BECAUSE THIS SOFTWARE IS LICENSED FREE OF CHARGE, THERE IS NO WARRANTY
FOR THE SOFTWARE, TO THE EXTENT PERMITTED BY APPLICABLE LAW. EXCEPT
WHEN OTHERWISE STATED IN WRITING THE COPYRIGHT HOLDERS AND/OR OTHER
PARTIES PROVIDE THE SOFTWARE "AS IS" WITHOUT WARRANTY OF ANY KIND,
EITHER EXPRESSED OR IMPLIED, INCLUDING, BUT NOT LIMITED TO, THE
IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR
PURPOSE. THE ENTIRE RISK AS TO THE QUALITY AND PERFORMANCE OF THE
SOFTWARE IS WITH YOU. SHOULD THE SOFTWARE PROVE DEFECTIVE, YOU ASSUME
THE COST OF ALL NECESSARY SERVICING, REPAIR, OR CORRECTION.

IN NO EVENT UNLESS REQUIRED BY APPLICABLE LAW OR AGREED TO IN WRITING
WILL ANY COPYRIGHT HOLDER, OR ANY OTHER PARTY WHO MAY MODIFY AND/OR
REDISTRIBUTE THE SOFTWARE AS PERMITTED BY THE ABOVE LICENCE, BE LIABLE
TO YOU FOR DAMAGES, INCLUDING ANY GENERAL, SPECIAL, INCIDENTAL, OR
CONSEQUENTIAL DAMAGES ARISING OUT OF THE USE OR INABILITY TO USE THE
SOFTWARE (INCLUDING BUT NOT LIMITED TO LOSS OF DATA OR DATA BEING
RENDERED INACCURATE OR LOSSES SUSTAINED BY YOU OR THIRD PARTIES OR A
FAILURE OF THE SOFTWARE TO OPERATE WITH ANY OTHER SOFTWARE), EVEN IF
SUCH HOLDER OR OTHER PARTY HAS BEEN ADVISED OF THE POSSIBILITY OF SUCH
DAMAGES.

=head1 ACKNOWLEDGMENTS

Many thanks to:

=over 4

=item * Peter Bircher & Cristian Tuduce for several bug fixes

=item * Mark Greenheigh for the prompt and precise bug reports

=item * Jose Pedro Oliveria for the build and release fixes

=back
