=pod

=head1 NAME

C<check_updates> - a Nagios plugin to check if Red Hat or Fedora system
is up-to-date

=head1 DESCRIPTION

check_updates is a Nagios plugin to check if Red Hat or Fedora system
is up-to-date

=head1 VERSION

Version 1.7.5

=head1 SYNOPSIS

  check_updates [OPTIONS]

  -?, --usage
    Print usage information
  -h, --help
    Print detailed help screen
  -V, --version
    Print version information
  --extra-opts=[<section>[@<config_file>]]
    Section and/or config_file from which to load extra options (may repeat)
  --boot-check
    Check if the machine was booted with the newest kernel (default)
  --boot-check-warning
    Like --boot-check but state is warning instead of critical
  --no-boot-check
    Do not complain if the machine was booted with an old kernel
  --clean
    Cleans YUM/DNF caches
  -d, --debug
    Enables debugging messages
  -w, --warning=INTEGER
    Exit with WARNING status if more than INTEGER updates are available
  -c, --critical=INTEGER
    Exit with CRITICAL status if more than INTEGER updates are available
  --security-only
    Ignores non-security updates
  -a, --yum-arguments=STRING
    specific Yum arguments as STRING
  -t, --timeout=INTEGER
    Seconds before plugin times out (default: 15)
  -q, --quiet
    Do not print package list
  -v, --verbose
    Show details for command-line debugging (can repeat up to 3 times)

=head1 OPTIONS

  -?, --usage                              Print usage information

  -h, --help                               Print detailed help screen

  -V, --version                            Print version information

  --extra-opts=[<section>[@<config_file>]] Section and/or config_file from which to load extra options (may repeat)

  --boot-check                             Check if the machine was booted with the newest kernel (default)

  --boot-check-warning                     Like --boot-check but state is warning instead of critical

  --no-boot-check                          Do not complain if the machine was booted with an old kernel

  --clean                                  Cleans YUM/DNF caches

  -d, --debug                              Enables debugging messages

  -w, --warning=INTEGER                    Exit with WARNING status if more than INTEGER non-security updates are available

  -c, --critical=INTEGER                   Exit with CRITICAL status if more than INTEGER non-security updates are available

  --security-only                          Ignores non-security updates

  -a, --yum-arguments=STRING               Specifies additional arguments for Yum.
                                           Arguments containing spaces must be quoted
                                           (e.g., ./check_updates -a "-d 20")

  -t, --timeout=INTEGER                    Seconds before plugin times out (default: 15)

  -q, --quiet                              Do not print package list

  -v, --verbose                            Show details for command-line debugging (can repeat up to 3 times)

Security updates always force a CRITICAL state

=head1 SECURITY UPDATES

If yum's security plugin is available

=head1 EXAMPLE

check_updates

check_updates checks if the system is up-to-date

=head1 DIAGNOSTICS

You can specify --verbose option (-v) multiple times to increase
program verbosity.

=head1 EXIT STATUS

0 if OK, 1 in case of a warning, 2 in case of a critical status and 3
in case of an unknown problem

=head1 DEPENDENCIES

check_updates depends on

=over 4

=item * Carp

=item * English

=item * Getopt::Long

=item * Monitoring::Plugin

=item * Monitoring::Plugin::Getopt

=item * Monitoring::Plugin::Threshold

=item * POSIX

=item * Readonly

=back

=head1 INCOMPATIBILITIES

None reported.

=head1 SEE ALSO

Nagios documentation

=head1 BUGS AND LIMITATIONS

Some versions of yum deliver a wrong number of security updates. For example

        $ yum --security  check-update
        Loaded plugins: downloadonly, product-id, rhnplugin, security
        This system is receiving updates from RHN Classic or RHN Satellite.
        Limiting package lists to security relevant ones
        No packages needed for security; 7 packages available

        mysql-libs.i686                                  5.1.73-5.el6_6                                   rhel-x86_64-server-6

Either is mysql-libs a security update (and the text should report it) or the package is wrongly listed. If yum delivers a wrong count, the plugin will do the same.

Please report any bugs or feature requests to matteo@corti.li,
or through the web interface at https://github.com/matteocorti/check_updates/issues

Be sure to include the output produced by the plugin with the --verbose option:

  check_updates -v -v -v

=head1 AUTHOR

Matteo Corti <matteo@corti.li>

=head1 LICENSE AND COPYRIGHT

Copyright (c) 2007-2016, Matteo Corti

This module is free software; you can redistribute it and/or modify it
under the terms of GNU general public license (gpl) version 3 or (at
your option) any later version.
See the LICENSE file for details.

=head1 DISCLAIMER OF WARRANTY

BECAUSE THIS SOFTWARE IS LICENSED FREE OF CHARGE, THERE IS NO WARRANTY
FOR THE SOFTWARE, TO THE EXTENT PERMITTED BY APPLICABLE LAW. EXCEPT
WHEN OTHERWISE STATED IN WRITING THE COPYRIGHT HOLDERS AND/OR OTHER
PARTIES PROVIDE THE SOFTWARE "AS IS" WITHOUT WARRANTY OF ANY KIND,
EITHER EXPRESSED OR IMPLIED, INCLUDING, BUT NOT LIMITED TO, THE
IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR
PURPOSE. THE ENTIRE RISK AS TO THE QUALITY AND PERFORMANCE OF THE
SOFTWARE IS WITH YOU. SHOULD THE SOFTWARE PROVE DEFECTIVE, YOU ASSUME
THE COST OF ALL NECESSARY SERVICING, REPAIR, OR CORRECTION.

IN NO EVENT UNLESS REQUIRED BY APPLICABLE LAW OR AGREED TO IN WRITING
WILL ANY COPYRIGHT HOLDER, OR ANY OTHER PARTY WHO MAY MODIFY AND/OR
REDISTRIBUTE THE SOFTWARE AS PERMITTED BY THE ABOVE LICENCE, BE LIABLE
TO YOU FOR DAMAGES, INCLUDING ANY GENERAL, SPECIAL, INCIDENTAL, OR
CONSEQUENTIAL DAMAGES ARISING OUT OF THE USE OR INABILITY TO USE THE
SOFTWARE (INCLUDING BUT NOT LIMITED TO LOSS OF DATA OR DATA BEING
RENDERED INACCURATE OR LOSSES SUSTAINED BY YOU OR THIRD PARTIES OR A
FAILURE OF THE SOFTWARE TO OPERATE WITH ANY OTHER SOFTWARE), EVEN IF
SUCH HOLDER OR OTHER PARTY HAS BEEN ADVISED OF THE POSSIBILITY OF SUCH
DAMAGES.

=head1 ACKNOWLEDGMENTS

Many thanks to:

=over 4

=item * Peter Bircher & Cristian Tuduce for several bug fixes

=item * Mark Greenheigh for the prompt and precise bug reports

=item * Jose Pedro Oliveria for the build and release fixes

=item * Tomas Edwardsson for a patch fixing the detection of RH EL 6 systems

=item * Cott Lang for the Amazon Linux patch

=item * Joop Boonen for the yum arguments patch

=item * Franky Van Liedekerke for the perfomance data and security plugin patch and for the openvz kernels patch

=item * Andreas Dijkman for the Oracle UEK patch

=item * PhiBo (https://github.com/phibos) for the --boot-check-warning patch

=back
